services:
  app-outsera:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-outsera
    ports:
      - "3000:3000"
    command: node src/index.js

  app-outsera-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: app-outsera-test
    command: npm test
    # O container vai rodar o comando e encerrar
    restart: "no"